### PR TITLE
Separate TomoPy versions into different branches

### PR DESCRIPTION
**Pull request by dreycenfoiles**
This PR changes the Azure pipeline so that tomopy.github.io will have a different branch for each different TomoPy version being benchmarked. If the branch does not already exist, it will be created.

### CODE REVIEW

**Review by carterbox — CHANGES_REQUESTED** [review]
Please remove website submodule. Also see if `git switch` can replace your bash script.

**Review by carterbox — CHANGES_REQUESTED** [review]
You cannot use `checkout -B`. From the docs:

> If -B is given, <new_branch> is created if it doesn’t exist; otherwise, it is reset.

`-B` resets an existing branch. In other words, the second worker would erase the commits from the first worker to complete, and all previous commits on the branch would be erased back to the fork from master.

**Comment by dreycenfoiles** [comment]
Okay, I don't think we're able to use `git switch`, either, then. From the `git-switch` docs:
> -C <new-branch>
>--force-create <new-branch>
> Similar to --create except that if <new-branch> already exists, it will be reset to <start-point>. This is a convenient shortcut for:

**Comment by carterbox** [comment]
I think you could use `git checkout -B` if you guarantee that exactly one worker uses each branch. For example, make separate branches for GPU and CPU workers.

**Comment by carterbox** [comment]
This will work for now.

**Pull request merged**
